import type { Barber } from "@/types";

/**
 * Squire-sourced barber data keyed by city slug.
 * This file is auto-generated by scripts/generate-barber-files.ts
 * Run `npx tsx scripts/scrape-squire.ts` then `npx tsx scripts/generate-barber-files.ts` to populate.
 */
export const SQUIRE_BARBERS: Record<string, Barber[]> = {};
